name: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT(OpenResty, Tarantool) with syntax Twig/Jinja/Django/Liquid."
destination: ./build
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io/"
# remote_theme: poole/hyde
theme: minima
header_pages:
  - docs/syntax.md
  - docs/api.md
  - docs/cli.md
