name: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT (OpenResty, Tarantool) with syntax Twig/Jinja/Django/Liquid."
# destination: ./build
tagline: "Template Engine"
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io"
remote_theme: bzick/jekyll-docs-theme@v1.0.0-beta.5
links:
  pages:
    - title: Syntax
      url: /docs/syntax
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/unifire-app/pages
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/unifire-app/pages
    - title: Issues
      icon: bug
      url: https://github.com/unifire-app/pages/issues?state=open
# remote_theme: fongandrew/hydeout
# theme: minima

# sidebar_home_link:  true
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "default"
