name: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT(OpenResty, Tarantool) with syntax Twig/Jinja/Django/Liquid."
# destination: ./build
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io"
remote_theme: allejo/jekyll-docs-theme@v1.0.0-beta.4
links:
  header:
    - title: GitHub
      url: https://github.com/unifire-app/pages
  footer:
    - title: GitHub
      url: https://github.com/unifire-app/pages
    - title: Issues
      url: https://github.com/unifire-app/pages/issues?state=open
# remote_theme: fongandrew/hydeout
# theme: minima
# header_pages:
#   - url: docs/syntax.md
#     title: Syntax
#   - docs/api.md
#   - docs/cli.md

# sidebar_home_link:  true
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "default"
