name: "Aspect Lua Template"
description: "Aspect is a compiling template engine for Lua and LuaJIT (OpenResty, Tarantool) with syntax Twig/Jinja/Django/Liquid."
tagline: "Template Engine"
encoding: UTF-8
markdown: kramdown
url: "https://unifire-app.github.io"
remote_theme: bzick/jekyll-docs-theme

# theme configuration

project:
  download_url: https://github.com/unifire-app/aspect/releases
  download_text: Download

license:
  software: BSD 3 Clause
  software_url: https://opensource.org/licenses/BSD-3-Clause

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/

links:
  pages:
    - title: Syntax
      url: /syntax.md
    - title: Tagtags.mds
      url: /tags.md
    - title: Filters
      url: /filters
    - title: Funcs
      url: /funcs
    - title: Tests
      url: /tests
    - title: API
      url: /api
    - title: CLI
      url: /cli
  header:
    - title: '<img src="https://travis-ci.org/unifire-app/aspect.svg?branch=master" />'
      url: https://travis-ci.org/unifire-app/aspect
    - title: '<img src="https://codecov.io/gh/unifire-app/aspect/branch/master/graph/badge.svg" />'
      url: https://codecov.io/gh/unifire-app/aspect
    - title: '<img src="https://img.shields.io/badge/LuaRocks-Aspect-blue" />'
      url: https://luarocks.org/modules/unifire/aspect
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/unifire-app/pages
    - title: Issues
      icon: bug
      url: https://github.com/unifire-app/pages/issues?state=open

icons:
  favicon: docs/aspect.png
